// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzutedgiqmveijdwrnjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56dXRlZGdpcW12ZWlqZHdybmp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODU5NzYsImV4cCI6MjA2ODM2MTk3Nn0.Sg0c4KPsN6eJp359IZtV9wc7WTiYoouvIOao8gZjGQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});